spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
  profiles:
    active: local
  application:
    name: Notifications-application
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USER}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    producer:
      bootstrap-servers: ${bootstrap_servers}
      client-id: NotifierClient
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      batch-size: 16384
      buffer-memory: 335544432
      linger-ms: 1
      enable-Idempoyence: true
      transactionalId: NotificationTransId
    consumer:
      bootstrap-servers: ${bootstrap_servers}
      client-id: NotifierClient
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      isolation-level: read_committed
      max-poll-records: 18
      heartbeat-interval: 6000

kafka:
  topic:
    json:
      name: notification-json-demo55
      groupId: NotificationjsonemoGroup

server:
  port: 8083